=== alex-beaverg/solvd_laba_2023-02_second_project/src/main/resources/xml_data/new_employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="PackageType"> </xs:complexType>

    <xs:complexType name="PackagesType">
        <xs:sequence>
            <xs:element name="package" type="PackageType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AddressType">
        <xs:all>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="street" type="xs:string"/>
            <xs:element name="house" type="xs:int"/>
            <xs:element name="flat" type="xs:int"/>
            <xs:element name="zipCode" type="xs:int"/>
            <xs:element name="country" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="PassportType">
        <xs:all>
            <xs:element name="number" type="xs:string"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="PersonInfoType">
        <xs:all>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="age" type="xs:int"/>
            <xs:element name="passport" type="PassportType"/>
            <xs:element name="address" type="AddressType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="CompanyType">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="DepartmentType">
        <xs:all>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="company" type="CompanyType"/>
        </xs:all>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:sequence>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="experience" type="xs:string"/>
            <xs:element name="department" type="DepartmentType"/>
            <xs:element name="personInfo" type="PersonInfoType"/>
            <xs:element name="packages" type="PackagesType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:element name="employee" type="EmployeeType"/>
</xs:schema>

=== alex-beaverg/solvd_laba_2023-02_second_project/src/main/resources/xml_data/new_employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee id="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="new_employee.xsd">
    <position>MANAGER_1CAT</position>
    <experience>JUNIOR_PLUS</experience>
    <department id="1">
        <title>Order department</title>
        <company>
            <name>Delivery Service</name>
        </company>
    </department>
    <personInfo id="1">
        <firstName>Linda</firstName>
        <lastName>Bella</lastName>
        <age>25</age>
        <passport id="1">
            <number>II01055555</number>
        </passport>
        <address id="1">
            <city>Minsk</city>
            <street>Green street</street>
            <house>33</house>
            <flat>32</flat>
            <zipCode>220155</zipCode>
            <country>BELARUS</country>
        </address>
    </personInfo>
    <packages> </packages>
</employee>
